### ISSUE TITLE
Problem with es modules with next.js

### ISSUE THREAD

**Issue by Drapegnik** [matthewp/react-robot#13]
```
/sandbox/node_modules/react-robot/machine.js:1
import { useEffect, useState } from 'react';
       ^

SyntaxError: Unexpected token {
```

https://codesandbox.io/s/recursing-breeze-n34wd?file=/pages/index.js

**Comment by Drapegnik** [comment]
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/react-robot/machine.js
require() of ES modules is not supported.
require() of /node_modules/react-robot/machine.js from /.next/server/pages/temp.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename machine.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/react-robot/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at eval (webpack-internal:///react-robot:1:18)
    at Object.react-robot (.next/server/pages/temp.js:587:1)
    at __webpack_require__ (.next/server/pages/temp.js:23:31)
    at eval (webpack-internal:///./lib/fsm/index.ts:12:69)
    at Module../lib/fsm/index.ts (.next/server/pages/temp.js:187:1) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by Drapegnik** [comment]
works with `createUseMachine` from `robot-hooks`:
https://codesandbox.io/s/cool-currying-y3w6s?file=/pages/index.tsx:111-158

**Comment by Drapegnik** [comment]
looks similar to: https://github.com/matthewp/robot-hooks/pull/12

**Comment by matthewp** [comment]
robot-hooks has a CommonJS build and this does not (don't remember why). Should just port the build stuff over to here and have a CJS version.

**Comment by resusio** [comment]
What is the best workaround for this?

**Comment by Drapegnik** [comment]
@resusio, as a temporary solution I use `robot-hooks`:
```ts
import { useEffect, useState } from 'react';
import { createUseMachine } from 'robot-hooks';
export const useMachine = createUseMachine(useEffect, useState);
```

**Comment by matthewp** [comment]
Moving to the main repo. Still open to having a CJS build as some of the others do.
